[package]
name = "hub"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
bytes = "1.11.0"
dashmap = "6.1.0"
opus = "0.3.1"
tokio = { version = "1.49.0", features = ["full"] }
webrtc = "0.17.0"
